## 1. Fazendo leitura de arquivos CSV

### Lendo arquivos CSV

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'

In [3]:
dados_mercado = pd.read_csv(url)

In [4]:
dados_mercado.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

### Parâmetros da função read_csv

Alguns arquivos CSV não são separados por virgula, por este motivo precisamos passar o parametro sep = 'Caractere Separador'

In [5]:
# Esse parâmetro importa somente a quantidade de linhas desejadas:
dados_mercado2 = pd.read_csv(url, nrows = 3)

In [6]:
dados_mercado2

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  

[3 rows x 22 columns]

In [7]:
# Esse parâmetro importa somente a quantidade de colunas desejadas:
dados_mercado3 = pd.read_csv(url, usecols = ['Id', 'Year_Birth', 'Income'])

In [8]:
dados_mercado3

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

### Escrevendo arquivos CSV

In [9]:
dados_mercado3.to_csv('dados/clientes_mercado.csv')

In [10]:
pd.read_csv('dados/clientes_mercado.csv')

Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

O parâmetro index salva o arquivo com índices, para evitar isso temos que definir como False

In [11]:
dados_mercado3.to_csv('dados/clientes_mercado.csv', index = False)

In [12]:
pd.read_csv('dados/clientes_mercado.csv')

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

### Hora da Prática

* Verifique se o arquivo CSV está separado por vírgula ou ponto e vírgula.
* A codificação do arquivo é ISO-8859-1.
* As três primeiras linhas linhas do arquivo podem ser desconsideradas, pois o cabeçalho só começa na quarta linha.
* As 9 últimas linhas também podem ser desconsideradas, pois são apenas informações sobre onde os dados foram obtidos.
* Para deletar as últimas linhas é necessário adicionar o parâmetro engine='python'.

In [13]:
dados_saude = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/Pandas/main/dados_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter = 9, engine='python')

In [14]:
dados_saude.head()

Unidade da Federação     2008/Jan     2008/Fev     2008/Mar     2008/Abr  \
0             Rondônia   1388528,39   2931283,42   1541682,52   1525314,96   
1                 Acre    902416,00   1497206,26   1794028,48   1730469,42   
2             Amazonas   4735529,42   7118990,57   8196635,49   8259378,42   
3              Roraima    657889,53    777939,31    718688,03    839994,39   
4                 Pará  18864744,11  19553758,20  21937342,70  20842829,69   

      2008/Mai     2008/Jun     2008/Jul     2008/Ago     2008/Set  ...  \
0   1645953,84   1406150,68   3065279,01   3231494,61   3117178,63  ...   
1   1819443,92   1828496,00   2511754,59   2089107,14   2275708,53  ...   
2   7831399,90   8477273,62   9368858,72   9352532,70   9363099,35  ...   
3    862347,96    832440,66    996693,09    894271,18    910424,17  ...   
4  23249952,88  23240687,56  24002223,56  23341218,03  25172261,32  ...   

      2020/Jul     2020/Ago     2020/Set     2020/Out     2020/Nov  \
0  11824687,13  11733307,76  10201985,14   7955139,45   9357946,29   
1   3915193,20   3640142,82   3391242,21   4044321,44   3276590,10   
2  19769460,14  18059931,43  17841015,63  16408315,10  19895617,91   
3   3015488,30   2826486,18   2928043,91   3090313,73   3621031,05   
4  40804126,43  44385715,88  36820249,47  36965931,34  39004315,80   

      2020/Dez     2021/Jan     2021/Fev     2021/Mar          Total  
0   8880836,55   9266014,59   7730597,04  11023309,47   996411254,68  
1   3696997,31   3715723,12   3538427,92   4077045,92   450048530,47  
2  17765167,69  21430289,17  25917134,55  22032176,22  1917247936,05  
3   3454460,94   3266928,47   3519773,73   3985530,08   328876965,09  
4  38015145,79  38354682,46  37688314,23  33276392,89  4705309002,29  

[5 rows x 161 columns]

In [15]:
dados_saude.tail()

Unidade da Federação      2008/Jan      2008/Fev      2008/Mar  \
23   Mato Grosso do Sul    5377392,11    7002472,61    8423933,19   
24          Mato Grosso    4795299,01    8684882,23    7886243,14   
25                Goiás   15310637,29   22258668,68   21442515,75   
26     Distrito Federal    4745919,19    7632480,67    9647203,26   
27                Total  408424859,23  613174269,21  664043058,38   

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
23    8797487,68    9770421,80   10905392,18   10249299,82    9671553,45   
24    8794109,79    9231645,40   10221763,77    9163314,28    9243148,81   
25   20921212,45   21615970,67   18270043,87   20540517,13   20650730,67   
26   11098732,99   12891719,72   12850125,67   12565646,74   13710857,89   
27  686662861,42  715803639,49  752181563,64  764990284,76  750608648,28   

        2008/Set  ...       2020/Jul       2020/Ago       2020/Set  \
23   10218511,05  ...    18858844,44    19877080,68    19247894,51   
24    9052354,89  ...    16834650,98    19704915,36    20746227,60   
25   20868443,56  ...    40606222,82    46229357,10    44889588,33   
26   13165106,20  ...    25269773,34    26526196,39    20056592,11   
27  752962642,15  ...  1484010417,62  1514160823,72  1477904466,14   

         2020/Out       2020/Nov       2020/Dez       2021/Jan       2021/Fev  \
23    19497210,85    22023126,25    19629591,55    21693311,15    24337295,63   
24    22727405,20    20506039,58    19583803,46    19120141,68    18349376,92   
25    45529496,23    43037600,45    44147353,21    46127763,88    42742773,93   
26    20856249,30    20459325,27    22991567,76    23527050,29    22766952,62   
27  1489983146,21  1464196395,75  1441199605,05  1513991196,49  1500612299,36   

         2021/Mar            Total  
23    25168195,34    2324525096,33  
24    19611032,61    2180119781,15  
25    45592686,49    4973573613,47  
26    31831917,45    2592422853,56  
27  1687562138,38  172481760138,88  

[5 rows x 161 columns]

## 2. Utilizando Planilhas

### Lendo arquivos Excel

In [16]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'

In [17]:
dados_co2 = pd.read_excel(url)

In [18]:
dados_co2.head()

País ISO 3166-1 alpha-3     Ano  Total  Carvão  Oléo  Gás  Cimento  \
0  Afeganistão                AFG  1750.0    0.0     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751.0    0.0     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752.0    0.0     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753.0    0.0     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754.0    0.0     NaN   NaN  NaN      NaN   

   Queima  Outro  Per Capita  
0     NaN    NaN         NaN  
1     NaN    NaN         NaN  
2     NaN    NaN         NaN  
3     NaN    NaN         NaN  
4     NaN    NaN         NaN

Sabendo quais são as páginas da planilha e se existem mais de uma página

In [19]:
pd.ExcelFile(url).sheet_names

['emissoes_C02', 'emissoes_percapita', 'fontes']

### Parâmetros da função read_excel

O parâmetro sheet_name tem valor default igual a 0, trazendo sempre a primeira página da planilha e quando alterado podemos escolher a página que queremos importar

In [20]:
percapita = pd.read_excel(url, sheet_name='emissoes_percapita')

In [21]:
percapita.head()

País ISO 3166-1 alpha-3     Ano  Total  Carvão  Óleo  Gás  Cimento  \
0  Afeganistão                AFG  1750.0    NaN     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751.0    NaN     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752.0    NaN     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753.0    NaN     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754.0    NaN     NaN   NaN  NaN      NaN   

   Queima  Outro  
0     NaN    NaN  
1     NaN    NaN  
2     NaN    NaN  
3     NaN    NaN  
4     NaN    NaN

In [22]:
fontes = pd.read_excel(url, sheet_name='fontes')

In [23]:
fontes.head()

País ISO 3166-1 alpha-3     Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750.0  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751.0  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752.0  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753.0  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754.0  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

O parametro usecols permite selecionar apenas as colunas que desejamos

In [24]:
intervalo = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D')

In [25]:
intervalo

País ISO 3166-1 alpha-3     Ano         Total
0      Afeganistão                AFG  1750.0  0.000000e+00
1      Afeganistão                AFG  1751.0  0.000000e+00
2      Afeganistão                AFG  1752.0  0.000000e+00
3      Afeganistão                AFG  1753.0  0.000000e+00
4      Afeganistão                AFG  1754.0  0.000000e+00
...            ...                ...     ...           ...
63099       Global                WLD  2017.0  3.609674e+10
63100       Global                WLD  2018.0  3.682651e+10
63101       Global                WLD  2019.0  3.708256e+10
63102       Global                WLD  2020.0  3.526409e+10
63103       Global                WLD  2021.0  3.712385e+10

[63104 rows x 4 columns]

O parametro nrows permite selecionar apenas as linhas que desejamos

In [26]:
intervalo2 = pd.read_excel(url, sheet_name='emissoes_C02', usecols='A:D', nrows=10)

In [27]:
intervalo2

País ISO 3166-1 alpha-3     Ano  Total
0  Afeganistão                AFG  1750.0    0.0
1  Afeganistão                AFG  1751.0    0.0
2  Afeganistão                AFG  1752.0    0.0
3  Afeganistão                AFG  1753.0    0.0
4  Afeganistão                AFG  1754.0    0.0
5  Afeganistão                AFG  1755.0    0.0
6  Afeganistão                AFG  1756.0    0.0
7  Afeganistão                AFG  1757.0    0.0
8  Afeganistão                AFG  1758.0    0.0
9  Afeganistão                AFG  1759.0    0.0

### Escrevendo arquivos Excel

In [28]:
percapita.to_excel('dados/co2_percapita.xlsx', index = False)

In [29]:
pd.read_excel('dados/co2_percapita.xlsx')

País ISO 3166-1 alpha-3   Ano      Total     Carvão       Óleo  \
0      Afeganistão                AFG  1750        NaN        NaN        NaN   
1      Afeganistão                AFG  1751        NaN        NaN        NaN   
2      Afeganistão                AFG  1752        NaN        NaN        NaN   
3      Afeganistão                AFG  1753        NaN        NaN        NaN   
4      Afeganistão                AFG  1754        NaN        NaN        NaN   
...            ...                ...   ...        ...        ...        ...   
63099       Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100       Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101       Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102       Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103       Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gás   Cimento   Queima    Outro  
0            NaN       NaN      NaN      NaN  
1            NaN       NaN      NaN      NaN  
2            NaN       NaN      NaN      NaN  
3            NaN       NaN      NaN      NaN  
4            NaN       NaN      NaN      NaN  
...          ...       ...      ...      ...  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0  

[63104 rows x 10 columns]

### Lendo dados do Google Planilhas

In [30]:
# O Id da planilha google fica após ao /d/
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'

In [31]:
# /gviz/tq Acessa a API do google. tqx=out:csv transforma para csv. sheet trás os cabeçalhos da planilha
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [32]:
dados_co2_sheets = pd.read_csv(url)

In [33]:
dados_co2_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [34]:
# Indicando qual pagina da planilha que quero acessar
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'emisoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [35]:
percapita_sheets = pd.read_csv(url_percapita)

In [36]:
percapita_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [37]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [38]:
fontes_sheets = pd.read_csv(url_fontes)

In [39]:
fontes_sheets.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

### Hora da Prática

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Nós temos um link do Google Planilhas que contém dados importantes sobre as emissões de gás carbônico pelo mundo. O conjunto de dados foi obtido no Kaggle e consiste em emissões de CO2 per capita de todos os países do mundo de 1990 a 2019.

Neste desafio, a sua função é efetuar a leitura desse link do Google Planilhas e depois salvar o DataFrame obtido no formato CSV.

In [40]:
sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'

In [41]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [42]:
emissoes_co2 = pd.read_csv(url)

In [43]:
emissoes_co2.head()

Country Name country_code                     Region  \
0        Aruba          ABW  Latin America & Caribbean   
1  Afghanistan          AFG                 South Asia   
2       Angola          AGO         Sub-Saharan Africa   
3      Albania          ALB      Europe & Central Asia   
4      Andorra          AND      Europe & Central Asia   

                           Indicator Name           1990         1991  \
0  CO2 emissions (metric tons per capita)            NaN          NaN   
1  CO2 emissions (metric tons per capita)    191.745.115  167.681.579   
2  CO2 emissions (metric tons per capita)    553.661.955  544.538.649   
3  CO2 emissions (metric tons per capita)  1.819.541.634  124.281.022   
4  CO2 emissions (metric tons per capita)  7.521.831.658  723.537.924   

          1992           1993           1994           1995  ...  \
0          NaN            NaN            NaN            NaN  ...   
1   95.957.742      8.472.111     75.545.827     68.467.956  ...   
2  543.557.223     70.898.423    836.804.405    912.141.485  ...   
3  683.699.826    638.307.036    645.355.189    605.436.253  ...   
4   69.630.787  6.724.177.518  6.541.578.914  6.733.479.486  ...   

            2011           2012           2013           2014           2015  \
0            NaN            NaN            NaN            NaN            NaN   
1     29.650.624    259.295.334     18.562.366    146.235.617    172.896.741   
2    985.522.312    950.695.879  1.036.293.852  1.099.779.111    113.504.405   
3    166.942.319    150.324.046  1.533.630.039  1.668.337.371    160.377.515   
4  5.850.886.105  5.944.654.173  5.942.800.412  5.807.127.723  6.026.181.822   

            2016           2017           2018           2019         2019.1  
0            NaN            NaN            NaN            NaN            NaN  
1    149.789.334    131.694.556      1.632.953    159.824.372    159.824.372  
2  1.031.811.348     81.330.073    777.674.934    792.137.069    792.137.069  
3  1.557.664.358  1.788.786.074  1.782.738.948    169.224.832    169.224.832  
4  6.080.600.282  6.104.133.912  6.362.975.399  6.481.217.432  6.481.217.432  

[5 rows x 35 columns]

In [44]:
emissoes_co2.to_csv('dados/emissoes_co2_kaggle.csv', index = False)

## 3. Manipulando arquivos JSON

### Lendo arquivos JSON

In [48]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes.json'
dados_pacientes = pd.read_json(url)

In [49]:
dados_pacientes.head()

ID_paciente Doenca_cardiaca    IMC Fumante Consumo_alcool  AVC  \
0            0             Nao  16.60     Sim            Nao  Nao   
1            1             Nao  20.34     Nao            Nao  Sim   
2            2             Nao  26.58     Sim            Nao  Nao   
3            3             Nao  24.21     Nao            Nao  Nao   
4            4             Nao  23.71     Nao            Nao  Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Sexo_biologico  \
0             3            30                  Nao       Feminino   
1             0             0                  Nao       Feminino   
2            20            30                  Nao      Masculino   
3             0             0                  Nao       Feminino   
4            28             0                  Sim       Feminino   

  Faixa_etaria    Raca Diabetes Atividade_fisica Saude_geral  Horas_sono Asma  \
0        55-59  Branca      Sim              Sim   Muito boa           5  Sim   
1      80 ou +  Branca      Nao              Sim   Muito boa           7  Nao   
2        65-69  Branca      Sim              Sim    Razoavel           8  Sim   
3        75-79  Branca      Nao               No         Boa           6  Nao   
4        40-44  Branca      Nao              Sim   Muito boa           8  Nao   

  Doenca_renal Cancer_pele  
0          Nao         Sim  
1          Nao         Nao  
2          Nao         Nao  
3          Nao         Sim  
4          Nao         Nao

In [50]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/pacientes_2.json'
dados_pacientes2 = pd.read_json(url)

In [51]:
dados_pacientes2.head()

Pesquisa   Ano  \
0  Principais Indicadores de Doenca Cardiaca  2020   
1  Principais Indicadores de Doenca Cardiaca  2020   
2  Principais Indicadores de Doenca Cardiaca  2020   

                                           Pacientes  
0  {'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi...  
1  {'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_...  
2  {'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi...

### Normalizando arquivos JSON

In [52]:
# json_normalize passando o nome da coluna com elementos aninhados para
# solucionar nosso problema
df_normalizado = pd.json_normalize(dados_pacientes2['Pacientes'])

In [55]:
df_normalizado.head()

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0  01        55-59       Feminino  Branca  16.60     Sim            Nao   
1  02      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2  03        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

### Escrevendo arquivos JSON

In [56]:
df_normalizado.to_json('dados/historico_pacientes_normalizado.json')

### Hora da Prática

In [57]:
import requests
import json

In [58]:
dados_frutas = requests.get('https://fruityvice.com/api/fruit/all')

In [69]:
resultado = json.loads(dados_frutas.text)

In [70]:
df_frutas = pd.json_normalize(resultado)

In [71]:
df_frutas.head()

name  id      family         order      genus  nutritions.calories  \
0   Persimmon  52   Ebenaceae       Rosales  Diospyros                   81   
1  Strawberry   3    Rosaceae       Rosales   Fragaria                   29   
2      Banana   1    Musaceae  Zingiberales       Musa                   96   
3      Tomato   5  Solanaceae     Solanales    Solanum                   74   
4        Pear   4    Rosaceae       Rosales      Pyrus                   57   

   nutritions.fat  nutritions.sugar  nutritions.carbohydrates  \
0             0.0              18.0                      18.0   
1             0.4               5.4                       5.5   
2             0.2              17.2                      22.0   
3             0.2               2.6                       3.9   
4             0.1              10.0                      15.0   

   nutritions.protein  
0                 0.0  
1                 0.8  
2                 1.0  
3                 0.9  
4                 0.4

## 4. Lendo dados em HTML e XML

### Lendo páginas web

In [72]:
dados_html = pd.read_html('dados/movies_wikipedia.html')

In [74]:
# Trás todas as tabelas indexadas em uma lista, no caso essa página tinha
# 3 tabelas
dados_html

[                                                    0  \
 0                                                1998   
 1                                                1999   
 2                                                2000   
 3                                                2001   
 4                                                2002   
 5                                                2003   
 6                                                2004   
 7                                                2005   
 8                                                2005   
 9                                                2006   
 10                                               2006   
 11                                               2007   
 12                                               2008   
 13  .mw-parser-output .hlist dl,.mw-parser-output ...   
 
                                                     1  
 0                                          100 Movies  
 1            

In [75]:
type(dados_html)

list

In [76]:
len(dados_html)

3

In [81]:
top_filmes = dados_html[1]

In [82]:
top_filmes

Film  Release year              Director  \
0             Citizen Kane          1941          Orson Welles   
1               Casablanca          1942        Michael Curtiz   
2            The Godfather          1972  Francis Ford Coppola   
3       Gone with the Wind          1939        Victor Fleming   
4       Lawrence of Arabia          1962            David Lean   
..                     ...           ...                   ...   
118        Sophie's Choice          1982        Alan J. Pakula   
119  The Last Picture Show          1971     Peter Bogdanovich   
120     Do the Right Thing          1989             Spike Lee   
121           Blade Runner          1982          Ridley Scott   
122              Toy Story          1995         John Lasseter   

                              Production companies 1998 Rank 2007 Rank  
0                               RKO Radio Pictures         1         1  
1                            Warner Bros. Pictures         2         3  
2           Paramount Pictures, Alfran Productions         3         2  
3                  Selznick International Pictures         4         6  
4                                 Horizon Pictures         5         7  
..                                             ...       ...       ...  
118                              ITC Entertainment         -        91  
119                                BBS Productions         -        95  
120                  40 Acres and a Mule Filmworks         -        96  
121                The Ladd Company, Shaw Brothers         -        97  
122  Walt Disney Pictures, Pixar Animation Studios         -        99  

[123 rows x 6 columns]

### Escrevendo arquivos HTML

In [83]:
top_filmes.to_html('dados/top_filmes.html')

In [84]:
top_filmes.to_csv('dados/top_filmes_1998.csv', index = False)

In [85]:
pd.read_csv('dados/top_filmes_1998.csv')

Film  Release year              Director  \
0             Citizen Kane          1941          Orson Welles   
1               Casablanca          1942        Michael Curtiz   
2            The Godfather          1972  Francis Ford Coppola   
3       Gone with the Wind          1939        Victor Fleming   
4       Lawrence of Arabia          1962            David Lean   
..                     ...           ...                   ...   
118        Sophie's Choice          1982        Alan J. Pakula   
119  The Last Picture Show          1971     Peter Bogdanovich   
120     Do the Right Thing          1989             Spike Lee   
121           Blade Runner          1982          Ridley Scott   
122              Toy Story          1995         John Lasseter   

                              Production companies 1998 Rank 2007 Rank  
0                               RKO Radio Pictures         1         1  
1                            Warner Bros. Pictures         2         3  
2           Paramount Pictures, Alfran Productions         3         2  
3                  Selznick International Pictures         4         6  
4                                 Horizon Pictures         5         7  
..                                             ...       ...       ...  
118                              ITC Entertainment         -        91  
119                                BBS Productions         -        95  
120                  40 Acres and a Mule Filmworks         -        96  
121                The Ladd Company, Shaw Brothers         -        97  
122  Walt Disney Pictures, Pixar Animation Studios         -        99  

[123 rows x 6 columns]

### Lendo e escrevendo em XML

In [86]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/imdb_top_1000.xml'

In [87]:
dados_imdb = pd.read_xml(url)

In [89]:
dados_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [90]:
dados_imdb.to_xml('dados/filmes_imdb.xml')

### Hora da Prática

In [91]:
url = 'https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o'

In [92]:
dados_ambientais = pd.read_html(url)[0]

In [93]:
dados_ambientais.head()

Unnamed: 0 Posição País (ou território dependente) Estimativa da ONU  Data  \
0         NaN       1                           Índia     1 429 921 746  2023   
1         NaN       2                           China     1 426 391 281  2023   
2         NaN       3                  Estados Unidos       339 987 103  2023   
3         NaN       4                       Indonésia       277 184 719  2023   
4         NaN       5                       Paquistão       240 215 932  2023   

   Estimativa Oficial  
0  Estimativa oficial  
1       Censo oficial  
2       Censo oficial  
3  Estimativa oficial  
4  Estimativa oficial

## 5. Tabalhando com Banco de Dados

In [94]:
import pandas as pd
import sqlalchemy

In [95]:
sqlalchemy.__version__

'1.4.32'

### Criando um banco de dados local

In [96]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [98]:
engine = create_engine('sqlite:///:memory:')

In [100]:
engine

Engine(sqlite:///:memory:)

### Escrevendo em um banco de dados

In [101]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [102]:
dados = pd.read_csv(url)

In [103]:
dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

In [104]:
# Salvando a tabela com o nome clientes dentro da nossa engine que foi criada
dados.to_sql('Clientes', engine, index = False)

438463

In [105]:
# Essa função permite acessarmos as tabelas da engine
inspector = inspect(engine)

In [106]:
# Ver quais os nomes das tabelas presentes no nosso banco de dados
print(inspector.get_table_names())

['Clientes']


### Lendo uma consulta SQL

In [107]:
query = 'SELECT * FROM Clientes WHERE Categoria_de_renda = "Empregado"'

In [110]:
# Para fazer a consulta precisamos usar a função read_sql e passar como 
# parâmetro a consulta que desejamos (query) e nosso banco de dados (engine)
empregados = pd.read_sql(query, engine)

In [111]:
empregados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008815     46   Ensino superior         Casado                2   
4     5112956     46   Ensino superior         Casado                2   

  Categoria_de_renda       Ocupacao  Anos_empregado  Rendimento_anual  \
0          Empregado          Outro              12          427500.0   
1          Empregado          Outro              12          427500.0   
2          Empregado      Segurança               3          112500.0   
3          Empregado  Contabilidade               2          270000.0   
4          Empregado  Contabilidade               2          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          1  Casa/apartamento próprio  
4          1  Casa/apartamento próprio

In [112]:
# Para salvar a tabela utilizar to_sql, passando o parâmetro 'con' igual a
# nossa engine que foi criada
empregados.to_sql('empregados', con=engine, index=False)

226059

In [113]:
# read_sql_table para ler uma tabela inteira, passando a engine que está nossa
# tabela.
pd.read_sql_table('empregados', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

In [114]:
# Podemos também visualizar só algumas colunas da tabela
pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

### Atualizando um banco de dados

In [115]:
query = 'SELECT * FROM Clientes'

In [116]:
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [117]:
# Queremos deletar a primeira linha do nosso banco de dados.
# Usamos o connect para conectar com o banco de dados e o execute faz com que
# execute a query que criamos
query = 'DELETE FROM Clientes WHERE ID_Cliente =5008804'
with engine.connect() as conn:
    conn.execute(query)

In [118]:
pd.read_sql_table('Clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [119]:
# Queremos agora atualizar o cadastro de um cliente que mudou seu grau
# de escolaridade de ensino médio para ensino superior
query = 'UPDATE Clientes SET Grau_escolaridade="Ensino Superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    conn.execute(query)

In [120]:
pd.read_sql_table('Clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino Superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

### Hora da Prática

Você é responsável por criar um banco de dados local de clientes para uma instituição financeira. Temos o arquivo CSV com os dados de clientes.

Sua missão é:

1.Criar o banco de dados local com a biblioteca SQLAlchemy.

2.Escrever os dados do arquivo CSV neste banco de dados local.

3.Realizar três atualizações no banco de dados:

Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

Criar um novo registro de cliente seguindo as especificações abaixo:
ID_Cliente: 6850985
Idade: 33
Grau_escolaridade: Doutorado
Estado_civil: Solteiro
Tamanho_familia: 1
Categoria_de_renda: Empregado
Ocupacao: TI
Anos_empregado: 2
Rendimento_anual: 290000
Tem_carro: 0
Moradia: Casa/apartamento próprio

In [121]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [122]:
dados = pd.read_csv(url)

In [128]:
dados

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [124]:
engine2 = create_engine('sqlite:///:memory:')

In [127]:
dados.to_sql('Clientes', engine2, index = False)

438463

In [135]:
pd.read_sql_table('Clientes',engine2)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [143]:
query = 'UPDATE Clientes SET Rendimento_anual=300000.0 WHERE ID_Cliente=6840104'
with engine2.connect() as conn:
    conn.execute(query)

In [146]:
pd.read_sql_table('Clientes', engine2)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          300000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [147]:
query = 'DELETE FROM Clientes WHERE ID_Cliente=5008809'
with engine2.connect() as conn:
    conn.execute(query)

In [148]:
pd.read_sql_table('Clientes', engine2)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          300000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [149]:
query = 'INSERT INTO Clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'
with engine2.connect() as conn:
    conn.execute(query)

In [150]:
pd.read_sql_table('Clientes', engine2)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   
438462     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   
438462            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  
438462          290000.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]